steps:
  # 1. Run Linter
  - name: 'python:3.11-slim'
    id: 'Run Linter'
    entrypoint: 'bash'
    args:
      - -c
      - |
        pip install flake8
        flake8 --ignore=E501 .

  # 2. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/cicd-learning-repo/cicd-learning-app:${COMMIT_SHA}'
      - '.'
    waitFor: ['Run Linter']

  # 2. Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/cicd-learning-repo/cicd-learning-app:${COMMIT_SHA}'
    id: 'Push to Artifact Registry'

  # 3. Update the Cloud Run Job with the new image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'update'
      - 'cicd-learning-job'
      - '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/cicd-learning-repo/cicd-learning-app:${COMMIT_SHA}'
      - '--region=us-central1'
    id: 'Update Cloud Run Job'